<?xml version="1.0"?>
<robot name="j_first_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<xacro:property name="chassisHeight" value="0.1"/>
	<xacro:property name="chassisLength" value="0.4"/>
	<xacro:property name="chassisWidth" value="0.2"/>
	<xacro:property name="chassisMass" value="25"/>

	<xacro:property name="casterRadius" value="0.05"/>
	<xacro:property name="casterMass" value=".5"/>

	<xacro:property name="wheelWidth" value="0.05"/>
	<xacro:property name="wheelRadius" value="0.1"/>
	<xacro:property name="wheelPos" value="0.2"/>
	<xacro:property name="wheelMass" value=".5"/>

	<xacro:property name="cameraSize" value="0.05"/>
	<xacro:property name="cameraMass" value="0.1"/>
	
	<xacro:property name="laserSize" value="0.05"/>
	<xacro:property name="laserMass" value="0.1"/>

	 <xacro:include filename="$(find jitu_bot_description)/urdf/jitu_bot.gazebo" />
	 <xacro:include filename="$(find jitu_bot_description)/urdf/materials.xacro" />
	 <xacro:include filename="$(find jitu_bot_description)/urdf/macros.xacro" />

	<link name="chassis">
	  <collision> 
	    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
		    <geometry> 
		      	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
		    </geometry> 
	  </collision>
		  <visual> 
		    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
		    <geometry> 
		      	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
		    </geometry> 
		    	<material name="orange"/>
		  </visual>
	  <inertial> 
		    <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
		    <mass value="${chassisMass}"/> 
		    <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
		  </inertial>
	</link>
	
	<link name="footprint" />

	<joint name="base_joint" type="fixed">
		  <parent link="footprint"/>
		  <child link="chassis"/>
	</joint>
	
	<joint name="chassis_joint" type="fixed">
		  <parent link="chassis"/>
		  <child link="caster_wheel"/>
	</joint>
	<!-- **********************************-->
	<!-- ********Added by Mr. J************-->
	
	<joint name="Camfoot" type="fixed">
			<axis xyz="0.2 1 0" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="chassis"/>
			<child link="camera"/>
	</joint>
	
	<joint name="Camfoot2" type="fixed">
			<axis xyz="0.2 1 0" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="chassis"/>
			<child link="camera2"/>
	</joint>
	

	<joint name="fixed2" type="fixed">
		  <parent link="chassis"/>
		  <child link="caster_wheel2"/>
	</joint>
	<!-- ********Added by Mr. J************-->
	<!-- **********************************-->

	<link name="caster_wheel">
	  <collision>
	    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <geometry>
	      <sphere radius="${casterRadius}"/>
	    </geometry>
	  </collision>
	  
	  <visual>
	    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <geometry>
	      <sphere radius="${casterRadius}"/>
	    </geometry>
	    <material name="red"/>
	  </visual>

	  <inertial>
	    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <mass value="${casterMass}"/>
	    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
	  </inertial>
	</link>
	
	<link name="camera">
	  <collision>
		<origin xyz="0.1 0.1 0.1" rpy="0 0 0"/>
		
		<geometry>
		  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
		  
		</geometry>
	  </collision>

	  <visual>
		<origin xyz="0.2 0.0 0.1" rpy="0 0 0"/>
		<geometry>
		  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
		</geometry>
		<material name="blue"/>
	  </visual>

	  <inertial>
		<mass value="${cameraMass}" />
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
	  </inertial>
	</link>
	<!-- **********************************-->
	<!-- ********Added by Mr. J************-->
	
		<link name="camera2">
	  <collision>
		<origin xyz="0.1 0.1 0.1" rpy="0 0 0"/>
		
		<geometry>
		  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
		  
		</geometry>
	  </collision>

	  <visual>
		<origin xyz="-0.2 0.0 0.1" rpy="0 0 0"/>
		<geometry>
		  <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
		</geometry>
		
<!--    <material name="blue"/> -->
	  </visual>

	  <inertial>
		<mass value="${cameraMass}" />
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
	  </inertial>
	</link>
	
	<link name="caster_wheel2">
	  <collision>
	    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <geometry>
	      <sphere radius="${casterRadius}"/>
	    </geometry>
	  </collision>
	  
	  <visual>
	    <origin xyz="${casterRadius+chassisLength/2-2*casterRadius} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <geometry>
	      <sphere radius="${casterRadius}"/>
	    </geometry>
	    <material name="blue"/>
	  </visual>

	  <inertial>
	    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
	    <mass value="${casterMass}"/>
	    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
	  </inertial>
	</link>
	<!-- ********Added by Mr. J************-->
	<!-- **********************************-->
	
	<!-- ********* Laser ****************-->
	<!-- ********Added by Mr. J************-->
	
	
	<joint name="base_laser_link" type="fixed">
		<origin xyz="0.18 0.00 0.16" rpy="3.14159 0 0" />
		<parent link="chassis" />
		<child link="base_laser_link" />
	</joint>

  <link name="base_laser_link">
	    <collision>
		<origin xyz="0.4 0.1 0.1" rpy="0 0 0"/>
		
		<geometry>
		  <box size="${laserSize} ${laserSize} ${laserSize}"/>
		  
		</geometry>
	  </collision>
    <visual>
		
		  <geometry>
			<box size="0.02 0.03 0.03" />
		  </geometry>
		<material name="green" />
    </visual>
    <inertial>
		  <mass value="0.000001" />
		  <origin xyz="0 0 0" />
		  <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
			iyy="0.0001" iyz="0.0"
			izz="0.0001" />
    </inertial>
  </link>
  
  <!-- **********************************-->
  
	<wheel lr="left" tY="1"/>
	<wheel lr="right" tY="-1"/>

</robot>
